### ISSUE TITLE
Possible incompatibility found when HARF and Children & Pregnancy loaded

### ISSUE THREAD

**Issue by ghost** [TheButterfish/HairModdingPlus#2]
Hello! I've been running across an issue that apparently has been happening for a little while on my end now. There's a visible drawing conflict happening when Children & Pregnancy and Humanoid Alien Races Framework when loaded together with Hair Modding Plus. This happened prior to most recent updates if I'm remembering correctly, since I'm only just grabbing the January 10th release this week since I had the initial 1.2 update.

Color masking still works fine, but the "_back" hairs refuse to render. No errors about this issue pop up in-game, but this was found multiple times in the Player.log file while all 3 mods were active together:

```
ArgumentNullException: Value cannot be null.
Parameter name: mesh
  at UnityEngine.Graphics.DrawMeshNow (UnityEngine.Mesh mesh, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation, System.Int32 materialIndex) [0x0000d] in <5e1dfb686eb345078a588df96401afcc>:0 
  at UnityEngine.Graphics.DrawMeshNow (UnityEngine.Mesh mesh, UnityEngine.Vector3 position, UnityEngine.Quaternion rotation) [0x00001] in <5e1dfb686eb345078a588df96401afcc>:0 
  at Verse.GenDraw.DrawMeshNowOrLater (UnityEngine.Mesh mesh, UnityEngine.Vector3 loc, UnityEngine.Quaternion quat, UnityEngine.Material mat, System.Boolean drawNow) [0x0000c] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at ButterfishHairModdingPlus.Patch_Core.DrawBackHairLayer (Verse.PawnRenderer __instance, UnityEngine.Vector3& rootLoc, System.Single& angle, Verse.Rot4& headFacing, Verse.RotDrawMode& bodyDrawType, System.Boolean& portrait, System.Boolean& headStump) [0x001aa] in <44f0d669d57f4e0a859dd4001a851aa1>:0 
  at (wrapper dynamic-method) Verse.PawnRenderer.Verse.PawnRenderer.RenderPawnInternal_Patch6(Verse.PawnRenderer,UnityEngine.Vector3,single,bool,Verse.Rot4,Verse.Rot4,Verse.RotDrawMode,bool,bool,bool)
  at Verse.PawnRenderer.RenderPortrait () [0x00086] in <6326ac03f61f45efb3178f3bfd084139>:0 
  at RimWorld.PortraitRenderer.OnPostRender () [0x0000b] in <6326ac03f61f45efb3178f3bfd084139>:0 
UnityEngine.Camera:Render()
RimWorld.PortraitRenderer:RenderPortrait(Pawn, RenderTexture, Vector3, Single)
RimWorld.PortraitsCache:RenderPortrait(Pawn, RenderTexture, Vector3, Single)
RimWorld.PortraitsCache:Get(Pawn, Vector2, Vector3, Single, Boolean, Boolean)
RimWorld.Page_ConfigureStartingPawns:DrawPawnList(Rect)
RimWorld.Page_ConfigureStartingPawns:RimWorld.Page_ConfigureStartingPawns.DoWindowContents_Patch1(Page_ConfigureStartingPawns, Rect)
Verse.Window:InnerWindowOnGUI(Int32)
UnityEngine.GUI:CallWindowDelegate(WindowFunction, Int32, Int32, GUISkin, Int32, Single, Single, GUIStyle)
 
(Filename: <5e1dfb686eb345078a588df96401afcc> Line: 0)
```

All of the mods are the most recent updates as listed on Steam and the C&P GitLab.

It's not a game-breaking thing, I've clearly been playing this entire time without noticing it until I installed the Hamefura mod recently, but I just thought I'd let you know it's one very weird clash I've noticed in the week I've been trying to narrow down why the front half of the hairs were showing up only. If I happen to remove one or the other, HM+ will work just fine. I just have to weather through the current save with no back hair for now, seeing as I have alien pawn babies to rear up. 

I'm wondering if the B&C fix you're working on will also tackle this issue as well, seeing as that mod is a direct derivative of C&P?

**Comment by TheButterfish** [comment]
Hi, sorry for the late reply.

Since the time you've opened the issue, I've released a compatibility patch for the Babies and Children 1.2 mod (which also includes compatibility with Alien Races), which included testing it with the Children and Pregnancy mod as well. So far, it seems to be working fine. You could try out the latest release (v1.4.3) and see if it resolves your issue.

**Comment by ghost** [comment]
Hello, and thanks for replying! I've tried the latest release, and it still seems to be happening unfortunately. Back hairs textures just don't want to render when all three mods are loaded together, and I've tried different load orders that the mod settings would allow for. Still not seeing the back hair unless I disable one or the other, between C&P or HAR. Not sure what could be causing this weird conflict, but I've just had to continue my current saves with just front hair/bangs for now until it can be pinpointed...

(Also want to bring up a side note that I see someone else has experienced the "turret" graphical glitch when the Gradient Hair mod is enabled. I've seen it a couple of times when I had the mod enabled as well and can also confirm no matter which load order, I've had random gradients load in as turret icons instead of the gradient maps themselves. This happened with turrets from Vanilla Expanded series and even Vanilla itself when I tested a while ago. I figured it had to have been something up with Gradients itself and just decided to leave it be since someone mentioned Gradient Hair was also having some weird issues Character Editor. I guess it's a possibility the same could be happening with whatever recent updates happened with HAR while C&P is in limbo still? Not sure...)

**Comment by TheButterfish** [comment]
Just to confirm, are you referring to this mod for C&P?: https://ludeon.com/forums/index.php?topic=51258.0
If so, then I tested with a different baby/children related mod instead (https://steamcommunity.com/sharedfiles/filedetails/?id=1541438230), so I'll have to make another patch for it. Apologies for the confusion.

Interesting to hear that the turret glitch is not an isolated incident. If you don't mind, would you help me try to pinpoint the issue? Hopefully I'll be able to reproduce the issue myself so I can dig into it more.

Would you mind trying to load your save with only the following mods:
- Hair Modding Plus
- Gradient Hair
- one hair mod that utilizes Hair Modding Plus (and a pawn that uses it)
- one of the turret(?) mods, preferably the simplest one (any of them that have appeared as part of the bug)
- any mods that would break the savefile completely if removed
and see if the issue still crops up?

If it does, tell me which mods you used and I'll try to reproduce it.
If it doesn't, slowly add back your other mods - starting with the bigger, more complex ones - until the bug appears again. Then let me know which combination of mods seems to cause the bug.

And one more thing, try running your current modlist and savefile but only without Gradient Hair, see if the bug still happens to those pawns. This would help confirm or deny that it's related to my Gradient Hair compatibility patches.

Thank you very much.

**Comment by ghost** [comment]
Yes! That's exactly the one I've always been using. (Ever since the original creator Thirite introduced the mod, in fact).  I would have tried B&C, but I've weathered long enough w/ the original mod to the point my playthroughs would be quite boring w/out. Hopefully there'll be something that can be found out in what's turning off the back hair rendering, I'm still seeing that "hidden" error I posted at the top in all of my recent player logs still, so there's definitely a clash going on with those three mods together.

**Turret bug:** It's been quite a while since that issue happened, but I just thought I'd bring it up after finally seeing I wasn't the only one who encountered something strange. I am still in the midst of trying to find the setup that caused the turrets glitch again, and judging by everything I've tried so far, it's quite possible it was caused by any mod I no longer use, as I'm not having it happen in my current setup. 

The only things I can think of that I and the other user had in common in terms of mod usage at some point (judging by favorited workshop items) is RuntimeGC (not sure if it could be a cause), RF Body Type Extend (which I'm thinking COULD be one), and Awesome Inventory (another possibility, but not entirely sure. I just know I've moved back to the original RPG mod after it was updated due to some UI clashes w/ other mods Awesome Inventory was having for some reason...) 

Those mentioned mods in particular I haven't used since late 1.1/ early 1.2. I dropped them after getting the Royalty expansion. I might try to test those against the setup you requested to see if it happens again once I clear the last half of my current modlist as culprits. 

EDIT: Coming back in to say, I have even tried the mentioned ones in the requested setup, and amazingly they didn't trigger the turret glitch either? I'm beginning to think maybe it was something that got resolved in a mod update, but I won't know for sure unless I match up one of my old saves' modlist with Black Goat's current where it's happening to them. I have a really junky 1.1 save where it was happening, and a lot of the mods in that have either since been updated or abandoned outright...

**Comment by TheButterfish** [comment]
Alright, just needed to confirm you're using that particular mod. I will work on a compatibility patch for it soon.

As for the turret glitch, thanks for trying to troubleshoot it. It really is a strange glitch that it could be any mod's fault. I suppose we'd have to wait for Black Goat to troubleshoot his own modlist to get to the bottom of it.

**Comment by TheButterfish** [comment]
I've updated the mod to work with C&P now, you can get it from Steam or https://github.com/TheButterfish/HairModdingPlus/releases/tag/v1.4.4, let me know how it goes.

**Comment by ghost** [comment]
Working beautifly so far! Thank you very much for the work you've put into this! Rimworld desperately needed some better hair management, and it makes it so much easier to create way more interesting-looking pawns.

Hopefully this is the last issue on this you'll see from me, but I will be sure to bring up anything if it comes down to it. Still haven't been able to figure out what caused that turret glitch yet, but if Black Goat ever gets back to you with a list, I'll be happy to help narrowing possible culprits down. 

Thanks again!

**Comment by TheButterfish** [comment]
Glad to hear it! In that case, I'll be closing this issue.

**Comment by ghost** [comment]
One last thing! I just noticed this, and it's my fault for not getting back on in time to edit this in: I just noticed this... is the back hair supposed to disappear when hats are worn with mods like Hats Display Selection? (https://steamcommunity.com/sharedfiles/filedetails/?id=1542291825) 

I ask because this is in my current setup and is giving me a better FPS in-game than Show Hair with Hats recently. (I'm willing to try it with that mod again and see how it runs, but just thought I'd bring it up before you take a breather from the issue.)

**Comment by TheButterfish** [comment]
Funny you should mention that, since I'm working on a compatibility patch for Show Hair with Hats right now.

But yes, currently this mod replicates vanilla behavior when pawns wear hats i.e. hide hair when hats are worn.
Displaying the back hair is a duplicate but separate process from displaying the front hair, so mods that modify the front hair will not automatically modify the back hair.
That's why the back hair is still displaying vanilla behavior while the front hair has been modified.

I'll patch for Hats Display Selection as well then, thank you for bringing it up.

**Comment by TheButterfish** [comment]
I've released an update for compatibility with Show Hair with Hats and Hats Display Selection: https://github.com/TheButterfish/HairModdingPlus/releases/tag/v1.4.5
